[project]
name = "echo-state-network-experiments"
version = "0.1.0"
description = "Experiments with echo state networks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.6.2",
    "numpy>=2.3.0",
]
